server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
            scope: openid,profile
            client-name: Spring
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
        provider:
          spring:
            authorization-uri: "{baseUrl}/oauth2/authorize"
            token-uri: "{baseUrl}/oauth2/token"
            jwk-set-uri: "{baseUrl}/oauth2/jwks"
          okta:
            authorization-uri: "{baseUrl}/oauth2/v1/authorize"
            token-uri: "{baseUrl}/oauth2/v1/token"
            user-info-uri: "{baseUrl}/oauth2/v1/userinfo"
            jwk-set-uri: "{baseUrl}/oauth2/v1/keys"
